// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6kONbPStCpiFATBKD50WaGLmGyRrA2g',
    appId: '1:559679206408:web:ee6d830d352770c4ac4dbd',
    messagingSenderId: '559679206408',
    projectId: 'game2048-9e98c',
    authDomain: 'game2048-9e98c.firebaseapp.com',
    storageBucket: 'game2048-9e98c.firebasestorage.app',
    measurementId: 'G-RP6LWQPG6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbu8foBYbrD0ioB9yqIIyg90YACDYxMck',
    appId: '1:559679206408:android:f42ec7f5d4cef890ac4dbd',
    messagingSenderId: '559679206408',
    projectId: 'game2048-9e98c',
    storageBucket: 'game2048-9e98c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFVCO59rwdLvEouugMfgYBUJHjmC6JAs',
    appId: '1:559679206408:ios:b89ec30903bf755bac4dbd',
    messagingSenderId: '559679206408',
    projectId: 'game2048-9e98c',
    storageBucket: 'game2048-9e98c.firebasestorage.app',
    iosBundleId: 'com.example.game2048',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqFVCO59rwdLvEouugMfgYBUJHjmC6JAs',
    appId: '1:559679206408:ios:b89ec30903bf755bac4dbd',
    messagingSenderId: '559679206408',
    projectId: 'game2048-9e98c',
    storageBucket: 'game2048-9e98c.firebasestorage.app',
    iosBundleId: 'com.example.game2048',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK6kONbPStCpiFATBKD50WaGLmGyRrA2g',
    appId: '1:559679206408:web:5625f5e848bd4900ac4dbd',
    messagingSenderId: '559679206408',
    projectId: 'game2048-9e98c',
    authDomain: 'game2048-9e98c.firebaseapp.com',
    storageBucket: 'game2048-9e98c.firebasestorage.app',
    measurementId: 'G-N2CJT91Z6G',
  );
}
